"""md articles blog user post

Revision ID: b59cbdf15878
Revises: 35ae229e79dd
Create Date: 2026-08-31 02:21:16.408230

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b59cbdf15878"
down_revision: str | None = "35ae229e79dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("image_file", sa.String(length=20), nullable=False),
        sa.Column("password", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_user")),
        sa.UniqueConstraint("email", name=op.f("uq_blog_user_email")),
        sa.UniqueConstraint("username", name=op.f("uq_blog_user_username")),
    )
    op.create_index(op.f("ix_blog_user_id"), "blog_user", ["id"], unique=False)
    op.create_table(
        "blog_post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("date_posted", sa.DateTime(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["blog_user.id"],
            name=op.f("fk_blog_post_user_id_blog_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_post")),
    )
    op.create_index(op.f("ix_blog_post_id"), "blog_post", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blog_post_id"), table_name="blog_post")
    op.drop_table("blog_post")
    op.drop_index(op.f("ix_blog_user_id"), table_name="blog_user")
    op.drop_table("blog_user")
    # ### end Alembic commands ###
